### PR TITLE
Update cargo metadata now that this repo is in rust-lang-nursery

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by varkor** [comment]
This needs a rebase now that there's a new version of ena.

**Comment by alex** [comment]
@varkor resolved.

**Comment by varkor** [comment]
Following the convention in the Rust repository, you'll want to squash these commits (if you rebase rather than merge, you'll end up with a single commit, instead of having an unnecessary merge commit).

**Comment by alex** [comment]
Sorry about that, should be good now.

**Pull request merged**
